SELECT ISNULL(SUM(OL.COST),0) AS TOTAL, C.FIRST, C.LAST FROM AvaCustomer C LEFT JOIN
AvaOrder O ON C.CustomerId = O.CustomerId 
inner join AvaOrderLine OL ON O.OrderId = OL.ORDERID
WHERE O.CustDate BETWEEN DATEADD(mm,-6,GETDATE()) AND GETDATE()
GROUP BY C.first, C.LAST

--SELECT DATEADD(mm,-6,GETDATE())